; Proyecto PlatformIO del curso - Sistemas Lógicos UNSE 2026
; Placa: ESP32 DevKit (placa de cátedra)

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
